# Generated by Django 3.1.6 on 2021-02-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mapa',
            name='picture',
            field=models.ImageField(blank=True, upload_to='mapa/%Y/%m/%d'),
        ),
    ]
