version: '3.7'


services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - "1337:80"
    restart: always
    networks:
      - nginx_network
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn znajdki.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    networks:
      - nginx_network
      - postgres_network
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    networks:
      - postgres_network

networks:
   nginx_network:
     driver: bridge
   postgres_network:
     driver: bridge

volumes:
  postgres:
  static_volume:


