version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn znajdki.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
volumes:
  postgres:


