# Generated by Django 3.1.6 on 2021-07-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.CharField(default='Znajdka', max_length=250),
        ),
    ]
