# Generated by Django 3.1.6 on 2021-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rzeczy',
            name='image',
        ),
        migrations.AddField(
            model_name='rzeczy',
            name='image_obverse',
            field=models.ImageField(blank=True, upload_to='rzeczy/%Y/%m/%d', verbose_name='image_obverse'),
        ),
        migrations.AddField(
            model_name='rzeczy',
            name='image_reverse',
            field=models.ImageField(blank=True, upload_to='rzeczy/%Y/%m/%d', verbose_name='image_revers'),
        ),
    ]
