# Generated by Django 3.1.6 on 2021-04-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzeczy',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rzeczy',
            name='slug',
            field=models.SlugField(blank=True, unique_for_date='publish'),
        ),
    ]
