# Generated by Django 3.1.6 on 2021-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rzeczy',
            name='catalog_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rzeczy',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rzeczy',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rzeczy',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
