# Generated by Django 3.1.6 on 2021-05-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0002_auto_20210425_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='description',
            field=models.TextField(blank=True, default='Znajdka'),
        ),
    ]
