# Generated by Django 3.1.6 on 2021-06-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0002_auto_20210622_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzeczy',
            name='catalog_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
