# Generated by Django 3.1.6 on 2021-07-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0002_auto_20210709_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.CharField(blank=True, default='Znajdka', max_length=250),
        ),
    ]
