# Generated by Django 3.1.6 on 2021-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0004_auto_20210624_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzeczy',
            name='image_obverse',
            field=models.ImageField(default='poszukiwania/static/css/image/empty.png', upload_to='rzeczy/%Y/%m/%d', verbose_name='image_obverse'),
        ),
    ]
