# Generated by Django 3.1.6 on 2021-07-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0004_auto_20210712_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzeczy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rzeczy', to='poszukiwania.category'),
        ),
    ]
