# Generated by Django 3.1.6 on 2021-07-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poszukiwania', '0006_auto_20210624_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzeczy',
            name='image_obverse',
            field=models.ImageField(default='/static/empty.png', upload_to='rzeczy/%Y/%m/%d', verbose_name='image_obverse'),
        ),
        migrations.AlterField(
            model_name='rzeczy',
            name='image_reverse',
            field=models.ImageField(default='/static/empty.png', upload_to='rzeczy/%Y/%m/%d', verbose_name='image_revers'),
        ),
    ]
